-- 코드를 입력하세요
/*
SELECT a.FLAVOR
FROM FIRST_HALF a, JULY b
ORDER BY (
    SUM(a.TOTAL_ORDER + b.TOTAL_ORDER)
    
) DESC
LIMIT 3;

*/

SELECT a.FLAVOR
FROM FIRST_HALF a LEFT JOIN JULY b ON a.FLAVOR = b.FLAVOR
GROUP BY a.FLAVOR
ORDER BY SUM(a.TOTAL_ORDER + b.TOTAL_ORDER) DESC
LIMIT 3;