-- 코드를 작성해주세요

SELECT DISTINCT a.ID, a.EMAIL, a.FIRST_NAME, a.LAST_NAME
FROM DEVELOPERS a LEFT JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY IN ('Front End')   
) b ON 1=1
WHERE (a.SKILL_CODE & b.CODE) = b.CODE
ORDER BY ID ASC
